ARG IMAGE_NAME=hashicorp/terraform:1.2.4
FROM ${IMAGE_NAME}

# Install Ansible
RUN apk update \
    && apk add python3
RUN python3 -m ensurepip --upgrade \
    && python3 -m pip install --upgrade pip \
    && pip3 install ansible
# Add a user for correct Ansbile run as Jenkins
RUN adduser -s /sbin/nologin -S -D -u 113 jenkins

# Remove ENTRYPOINT
ENTRYPOINT []

CMD [ "/bin/sh" ]